# Generated by Django 3.2.8 on 2022-03-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
    ]
