# Generated by Django 3.2.8 on 2022-04-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
