# Generated by Django 3.2.8 on 2022-04-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20220406_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='shoose',
        ),
        migrations.AddField(
            model_name='player',
            name='tools',
            field=models.CharField(default='', max_length=30),
        ),
    ]
