# Generated by Django 3.2.8 on 2022-04-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20220406_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='tools',
            new_name='tool',
        ),
    ]
