# Generated by Django 3.2.8 on 2022-05-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_tools_player_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='openid',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='tool',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
